###
GET http://localhost:3003/api/users
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW4iLCJpZCI6IjYyMDNjODNlNTU5ZDVjYjA2MWIzMTcyYiIsImlhdCI6MTY0NDQxNTA1N30.2VcSoEHMhWFyfdhCX8z4tEbmxVdG1ldhNXrpiiVgOyc

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "quan",
    "name": "Quan",
    "password": "Test123"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "admin",
    "name": "Admin",
    "password": "admin"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "test",
    "name": "TEST",
    "password": "Test123"
}

###
DELETE http://localhost:3003/api/users/6203d01c4b755d810d7d08be
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF1YW4iLCJpZCI6IjYyMDNjODNlNTU5ZDVjYjA2MWIzMTcyYiIsImlhdCI6MTY0NDQxNTA1N30.2VcSoEHMhWFyfdhCX8z4tEbmxVdG1ldhNXrpiiVgOyc
content-type: application/json